### ISSUE TITLE
e2e-0008.params // raise MXNetError(py_str(_LIB.MXGetLastError()))

### ISSUE THREAD

**Issue by bkavlak** [chrisckri/InstanceSegmentation_Sentinel2#8]
Hi,

I am having errors below after I changed according to: https://github.com/chrieke/InstanceSegmentation_Sentinel2/issues/7

```
File "/home/user/anaconda3/envs/fcis/lib/python2.7/site-packages/mxnet/base.py", line 278, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [18:37:02] src/io/local_filesys.cc:209: Check failed: allow_null:  LocalFileSystem::Open "./output/fcis/coco/resnet_v1_101_coco_fcis_end2end_ohem/val2016/../train2016/e2e-0008.params": No such file or directory
Stack trace:
```
Should I have copied an ```e2e-0008.params``` file? If so, where should I find it?

Thanks in advance,

The full Log:

```
experiments/fcis/../../fcis/config/config.py:173: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  exp_config = edict(yaml.load(f))
/home/user/anaconda3/envs/fcis/lib/python2.7/site-packages/mxnet/numpy_op_signature.py:61: UserWarning: Some mxnet.numpy operator signatures may not be displayed consistently with their counterparts in the official NumPy package due to too-low Python version 2.7.17 |Anaconda, Inc.| (default, Oct 21 2019, 19:04:46) 
[GCC 7.3.0]. Python >= 3.5 is required to make the signatures display correctly.
  .format(str(sys.version)))
Namespace(cfg='experiments/fcis/cfgs/resnet_v1_101_coco_fcis_end2end_ohem.yaml', ignore_cache=False, shuffle=False, thresh=0.001, vis=False)
{'BINARY_THRESH': 0.4,
 'CLASS_AGNOSTIC': True,
 'MASK_SIZE': 21,
 'MXNET_VERSION': 'mxnet',
 'SCALES': [(600, 1000)],
 'TEST': {'BATCH_IMAGES': 1,
          'CXX_PROPOSAL': False,
          'HAS_RPN': True,
          'ITER': 2,
          'MASK_MERGE_THRESH': 0.5,
          'MIN_DROP_SIZE': 2,
          'NMS': 0.3,
          'PROPOSAL_MIN_SIZE': 2,
          'PROPOSAL_NMS_THRESH': 0.7,
          'PROPOSAL_POST_NMS_TOP_N': 2000,
          'PROPOSAL_PRE_NMS_TOP_N': 20000,
          'RPN_MIN_SIZE': 2,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'USE_GPU_MASK_MERGE': True,
          'USE_MASK_MERGE': True,
          'test_epoch': 8},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_IMAGES': 1,
           'BATCH_ROIS': -1,
           'BATCH_ROIS_OHEM': 128,
           'BBOX_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZATION_PRECOMPUTED': True,
           'BBOX_REGRESSION_THRESH': 0.5,
           'BBOX_STDS': [0.2, 0.2, 0.5, 0.5],
           'BBOX_WEIGHTS': array([1., 1., 1., 1.]),
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0,
           'BINARY_THRESH': 0.4,
           'CONVNEW3': True,
           'CXX_PROPOSAL': False,
           'ENABLE_OHEM': True,
           'END2END': True,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'FLIP': True,
           'GAP_SELECT_FROM_ALL': False,
           'IGNORE_GAP': False,
           'LOSS_WEIGHT': [1.0, 10.0, 1.0],
           'RESUME': False,
           'RPN_ALLOWED_BORDER': 0,
           'RPN_BATCH_SIZE': 256,
           'RPN_BBOX_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 2,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 300,
           'RPN_PRE_NMS_TOP_N': 6000,
           'SHUFFLE': True,
           'begin_epoch': 0,
           'end_epoch': 8,
           'lr': 0.0005,
           'lr_step': '5.33',
           'model_prefix': 'e2e',
           'momentum': 0.9,
           'warmup': True,
           'warmup_lr': 5e-05,
           'warmup_step': 250,
           'wd': 0.0005},
 'dataset': {'NUM_CLASSES': 81,
             'dataset': 'coco',
             'dataset_path': './data/coco',
             'image_set': 'train2016',
             'proposal': 'rpn',
             'root_path': './data',
             'test_image_set': 'val2016'},
 'default': {'frequent': 100, 'kvstore': 'device'},
 'gpus': '0',
 'network': {'ANCHOR_RATIOS': [0.5, 1, 2],
             'ANCHOR_SCALES': [4, 8, 16, 32],
             'FIXED_PARAMS': ['conv1',
                              'bn_conv1',
                              'res2',
                              'bn2',
                              'gamma',
                              'beta'],
             'FIXED_PARAMS_SHARED': ['conv1',
                                     'bn_conv1',
                                     'res2',
                                     'bn2',
                                     'res3',
                                     'bn3',
                                     'res4',
                                     'bn4',
                                     'gamma',
                                     'beta'],
             'IMAGE_STRIDE': 0,
             'NUM_ANCHORS': 12,
             'PIXEL_MEANS': array([ 91.55, 107.21, 116.17]),
             'RCNN_FEAT_STRIDE': 16,
             'RPN_FEAT_STRIDE': 16,
             'pretrained': '/home/doktar-ziya/FCIS/output/fcis/coco/resnet_v1_101_coco_fcis_end2end_ohem/e2e-symbol.json',
             'pretrained_epoch': 0},
 'output_path': './output/fcis/coco',
 'symbol': 'resnet_v1_101_fcis'}
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
num_images 2
prepare gt_sdsdb using 0.001788854599 seconds
generate cache_seg_inst using 0.121185064316 seconds
Traceback (most recent call last):
  File "experiments/fcis/fcis_end2end_test.py", line 12, in <module>
    test.main()
  File "experiments/fcis/../../fcis/test.py", line 57, in main
    args.vis, args.ignore_cache, args.shuffle, config.TEST.HAS_RPN, config.dataset.proposal, args.thresh, logger=logger, output_path=final_output_path)
  File "experiments/fcis/../../fcis/function/test_fcis.py", line 48, in test_fcis
    arg_params, aux_params = load_param(prefix, epoch, process=False)
  File "experiments/fcis/../../fcis/../lib/utils/load_model.py", line 56, in load_param
    arg_params, aux_params = load_checkpoint(prefix, epoch)
  File "experiments/fcis/../../fcis/../lib/utils/load_model.py", line 22, in load_checkpoint
    save_dict = mx.nd.load('%s-%04d.params' % (prefix, epoch))
  File "/home/user/anaconda3/envs/fcis/lib/python2.7/site-packages/mxnet/ndarray/utils.py", line 175, in load
    ctypes.byref(names)))
  File "/home/user/anaconda3/envs/fcis/lib/python2.7/site-packages/mxnet/base.py", line 278, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [18:37:02] src/io/local_filesys.cc:209: Check failed: allow_null:  LocalFileSystem::Open "./output/fcis/coco/resnet_v1_101_coco_fcis_end2end_ohem/val2016/../train2016/e2e-0008.params": No such file or directory
Stack trace:
  [bt] (0) /home/user/anaconda3/envs/fcis/lib/python2.7/site-packages/mxnet/libmxnet.so(dmlc::io::LocalFileSystem::Open(dmlc::io::URI const&, char const*, bool)+0x69f) [0x7f461bbd2eff]
  [bt] (1) /home/user/anaconda3/envs/fcis/lib/python2.7/site-packages/mxnet/libmxnet.so(dmlc::Stream::Create(char const*, char const*, bool)+0x27a) [0x7f461bbc56da]
  [bt] (2) /home/user/anaconda3/envs/fcis/lib/python2.7/site-packages/mxnet/libmxnet.so(MXNDArrayLoad+0xa7) [0x7f461ad45237]
  [bt] (3) /home/user/anaconda3/envs/fcis/lib/python2.7/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7f463f194ec0]
  [bt] (4) /home/user/anaconda3/envs/fcis/lib/python2.7/lib-dynload/../../libffi.so.6(ffi_call+0x22d) [0x7f463f19487d]
  [bt] (5) /home/user/anaconda3/envs/fcis/lib/python2.7/lib-dynload/_ctypes.so(_ctypes_callproc+0x4de) [0x7f4674c679de]
  [bt] (6) /home/user/anaconda3/envs/fcis/lib/python2.7/lib-dynload/_ctypes.so(+0x9b61) [0x7f4674c5db61]
  [bt] (7) /home/user/anaconda3/envs/fcis/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7f4674d06b83]
  [bt] (8) /home/user/anaconda3/envs/fcis/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x3bb9) [0x7f4674d9d199]

```

**Comment by bkavlak** [comment]
I guess the reason of this error is the missing ```params``` file. I created a ```train2016``` folder and copied ```fcis_coco-0000.params``` from FCIS repository to the folder, and it worked. I just run demo.py in the FCIS repository, succesfully. Maybe I should have run other examples to get ```params``` file there already.

**Comment by cryptSky** [comment]
Yes, unfortunately, I have the same issue. Looks like there is no file with pre-trained weights. 
@chrieke is it possible to get those somewhere?

**Comment by chrieke** [comment]
Thanks for bringing this up, here are the model weights, quite big at 223 MB. https://drive.google.com/file/d/1Y62BerMWV_C67oapOIXUzY0yK8XR7zRN/view?usp=sharing
Will look into it over the holidays. 

As a general recommendation I want to point towards https://github.com/facebookresearch/Detectron and other more modern models & implementations, the FCIS implementation is not really up to standard any more.

**Comment by bkavlak** [comment]
Thanks for the recommendation!

I am quite new to the deep learning field, but I'll definitely try to implement more recent models in the future. My goal is to detect agricultural fields from Sentinel-2 to increase accuracy in my crop mapping models. I guess the following paper and repository contain the most recent model on boundary detection from Sentinel-2:

https://arxiv.org/abs/1910.12023
https://github.com/feevos/resuneta
